# Generated by Django 6.1 on 2026-08-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='Utensils', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('food_type', models.CharField(choices=[('READY_FOOD', 'Ready Food (Puffs, Snacks, Bottled drinks)'), ('MADE_TO_ORDER', 'Made to Order (Tea, Coffee, Pizza, Burger)'), ('CONTACT_ORDER', 'Contact & Order (Bulk/Custom/Special Items)')], default='READY_FOOD', max_length=30)),
                ('preparation_time', models.IntegerField(default=5, help_text='Preparation time in minutes')),
                ('minimum_advance_time', models.IntegerField(default=5, help_text='Minimum advance ordering time in minutes')),
                ('current_stock', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=5)),
                ('maximum_stock', models.IntegerField(default=100)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('CONTACT_ORDER', 'Contact & Order Only'), ('PRE_ORDER', 'Pre-Order'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
