# Generated by Django 6.1 on 2026-08-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_days', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='e.g. SAEC-001', max_length=50)),
                ('customer_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('REGULAR_CUSTOMER', 'Regular Customer'), ('WALK_IN', 'Walk-in Counter Customer')], default='STUDENT', max_length=30)),
                ('order_source', models.CharField(choices=[('MOBILE', 'Flutter Mobile App'), ('POS', 'Cashier POS Counter')], default='MOBILE', max_length=20)),
                ('order_type', models.CharField(choices=[('READY_FOOD', 'Ready Food'), ('MADE_TO_ORDER', 'Made to Order'), ('CONTACT_ORDER', 'Contact & Order')], default='READY_FOOD', max_length=30)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('AWAITING_APPROVAL', 'Awaiting Cashier Approval'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_SUPPORT_REQUIRED', 'Payment Support Required'), ('CONFIRMED', 'Confirmed (In FCFS Queue)'), ('PREPARING', 'Preparing in Kitchen'), ('READY', 'Ready for Pickup'), ('DELIVERED', 'Delivered to Customer'), ('REJECTED', 'Rejected by Canteen'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when payment is verified and order enters FCFS queue', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business_days.businessday')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
