# Generated by Django 6.1 on 2026-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CASHIER', 'Canteen Cashier'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty / Staff')], default='STUDENT', max_length=20),
        ),
        migrations.DeleteModel(
            name='RegularCustomerProfile',
        ),
    ]
