# Generated by Django 6.1 on 2026-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_delete_regularcustomerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
