# Generated by Django 6.1 on 2026-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
