# Generated by Django 6.1 on 2026-08-13 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_days', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='closing_time',
            field=models.TimeField(default=datetime.time(15, 30)),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='daily_order_sequence',
            field=models.PositiveIntegerField(default=4820),
        ),
        migrations.AlterField(
            model_name='businessday',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
