# Generated by Django 6.1 on 2026-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_days', '0002_alter_businessday_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
